/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PoolsRouteImport } from './routes/pools'
import { Route as PocketRouteImport } from './routes/pocket'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as NavigatorRouteImport } from './routes/navigator'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KycRouteImport } from './routes/kyc'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CommandRouteImport } from './routes/command'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StockSymbolRouteImport } from './routes/stock.$symbol'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalRiskDisclosureRouteImport } from './routes/legal.risk-disclosure'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as GuidesDividendTrackingRouteImport } from './routes/guides.dividend-tracking'
import { Route as ApiWithdrawRequestRouteImport } from './routes/api/withdraw-request'
import { Route as ApiWithdrawApproveRouteImport } from './routes/api/withdraw-approve'
import { Route as ApiWalletInvestRouteImport } from './routes/api/wallet-invest'
import { Route as ApiTradeRouteImport } from './routes/api/trade'
import { Route as ApiQuoteRouteImport } from './routes/api/quote'
import { Route as ApiMpesaStkRouteImport } from './routes/api/mpesa-stk'
import { Route as ApiMpesaStatusRouteImport } from './routes/api/mpesa-status'
import { Route as ApiMpesaCallbackRouteImport } from './routes/api/mpesa-callback'
import { Route as ApiMpesaB2cResultRouteImport } from './routes/api/mpesa-b2c-result'
import { Route as ApiFeesRouteImport } from './routes/api/fees'
import { Route as ApiCandlesRouteImport } from './routes/api/candles'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminKycRouteImport } from './routes/admin.kyc'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiPublicCheckPriceAlertsRouteImport } from './routes/api/public/check-price-alerts'
import { Route as ApiPublicAmlScanRouteImport } from './routes/api/public/aml-scan'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolsRoute = PoolsRouteImport.update({
  id: '/pools',
  path: '/pools',
  getParentRoute: () => rootRouteImport,
} as any)
const PocketRoute = PocketRouteImport.update({
  id: '/pocket',
  path: '/pocket',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigatorRoute = NavigatorRouteImport.update({
  id: '/navigator',
  path: '/navigator',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KycRoute = KycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandRoute = CommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StockSymbolRoute = StockSymbolRouteImport.update({
  id: '/stock/$symbol',
  path: '/stock/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRiskDisclosureRoute = LegalRiskDisclosureRouteImport.update({
  id: '/legal/risk-disclosure',
  path: '/legal/risk-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesDividendTrackingRoute = GuidesDividendTrackingRouteImport.update({
  id: '/guides/dividend-tracking',
  path: '/guides/dividend-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWithdrawRequestRoute = ApiWithdrawRequestRouteImport.update({
  id: '/api/withdraw-request',
  path: '/api/withdraw-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWithdrawApproveRoute = ApiWithdrawApproveRouteImport.update({
  id: '/api/withdraw-approve',
  path: '/api/withdraw-approve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWalletInvestRoute = ApiWalletInvestRouteImport.update({
  id: '/api/wallet-invest',
  path: '/api/wallet-invest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTradeRoute = ApiTradeRouteImport.update({
  id: '/api/trade',
  path: '/api/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuoteRoute = ApiQuoteRouteImport.update({
  id: '/api/quote',
  path: '/api/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMpesaStkRoute = ApiMpesaStkRouteImport.update({
  id: '/api/mpesa-stk',
  path: '/api/mpesa-stk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMpesaStatusRoute = ApiMpesaStatusRouteImport.update({
  id: '/api/mpesa-status',
  path: '/api/mpesa-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMpesaCallbackRoute = ApiMpesaCallbackRouteImport.update({
  id: '/api/mpesa-callback',
  path: '/api/mpesa-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMpesaB2cResultRoute = ApiMpesaB2cResultRouteImport.update({
  id: '/api/mpesa-b2c-result',
  path: '/api/mpesa-b2c-result',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeesRoute = ApiFeesRouteImport.update({
  id: '/api/fees',
  path: '/api/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCandlesRoute = ApiCandlesRouteImport.update({
  id: '/api/candles',
  path: '/api/candles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AdminRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCheckPriceAlertsRoute =
  ApiPublicCheckPriceAlertsRouteImport.update({
    id: '/api/public/check-price-alerts',
    path: '/api/public/check-price-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAmlScanRoute = ApiPublicAmlScanRouteImport.update({
  id: '/api/public/aml-scan',
  path: '/api/public/aml-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/command': typeof CommandRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/mcp': typeof McpRoute
  '/navigator': typeof NavigatorRoute
  '/orders': typeof OrdersRoute
  '/pocket': typeof PocketRoute
  '/pools': typeof PoolsRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trade': typeof TradeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/api/candles': typeof ApiCandlesRoute
  '/api/fees': typeof ApiFeesRoute
  '/api/mpesa-b2c-result': typeof ApiMpesaB2cResultRoute
  '/api/mpesa-callback': typeof ApiMpesaCallbackRoute
  '/api/mpesa-status': typeof ApiMpesaStatusRoute
  '/api/mpesa-stk': typeof ApiMpesaStkRoute
  '/api/quote': typeof ApiQuoteRoute
  '/api/trade': typeof ApiTradeRoute
  '/api/wallet-invest': typeof ApiWalletInvestRoute
  '/api/withdraw-approve': typeof ApiWithdrawApproveRoute
  '/api/withdraw-request': typeof ApiWithdrawRequestRoute
  '/guides/dividend-tracking': typeof GuidesDividendTrackingRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/risk-disclosure': typeof LegalRiskDisclosureRoute
  '/legal/terms': typeof LegalTermsRoute
  '/stock/$symbol': typeof StockSymbolRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/aml-scan': typeof ApiPublicAmlScanRoute
  '/api/public/check-price-alerts': typeof ApiPublicCheckPriceAlertsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/command': typeof CommandRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/mcp': typeof McpRoute
  '/navigator': typeof NavigatorRoute
  '/orders': typeof OrdersRoute
  '/pocket': typeof PocketRoute
  '/pools': typeof PoolsRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trade': typeof TradeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/api/candles': typeof ApiCandlesRoute
  '/api/fees': typeof ApiFeesRoute
  '/api/mpesa-b2c-result': typeof ApiMpesaB2cResultRoute
  '/api/mpesa-callback': typeof ApiMpesaCallbackRoute
  '/api/mpesa-status': typeof ApiMpesaStatusRoute
  '/api/mpesa-stk': typeof ApiMpesaStkRoute
  '/api/quote': typeof ApiQuoteRoute
  '/api/trade': typeof ApiTradeRoute
  '/api/wallet-invest': typeof ApiWalletInvestRoute
  '/api/withdraw-approve': typeof ApiWithdrawApproveRoute
  '/api/withdraw-request': typeof ApiWithdrawRequestRoute
  '/guides/dividend-tracking': typeof GuidesDividendTrackingRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/risk-disclosure': typeof LegalRiskDisclosureRoute
  '/legal/terms': typeof LegalTermsRoute
  '/stock/$symbol': typeof StockSymbolRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/aml-scan': typeof ApiPublicAmlScanRoute
  '/api/public/check-price-alerts': typeof ApiPublicCheckPriceAlertsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/command': typeof CommandRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/mcp': typeof McpRoute
  '/navigator': typeof NavigatorRoute
  '/orders': typeof OrdersRoute
  '/pocket': typeof PocketRoute
  '/pools': typeof PoolsRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trade': typeof TradeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/api/candles': typeof ApiCandlesRoute
  '/api/fees': typeof ApiFeesRoute
  '/api/mpesa-b2c-result': typeof ApiMpesaB2cResultRoute
  '/api/mpesa-callback': typeof ApiMpesaCallbackRoute
  '/api/mpesa-status': typeof ApiMpesaStatusRoute
  '/api/mpesa-stk': typeof ApiMpesaStkRoute
  '/api/quote': typeof ApiQuoteRoute
  '/api/trade': typeof ApiTradeRoute
  '/api/wallet-invest': typeof ApiWalletInvestRoute
  '/api/withdraw-approve': typeof ApiWithdrawApproveRoute
  '/api/withdraw-request': typeof ApiWithdrawRequestRoute
  '/guides/dividend-tracking': typeof GuidesDividendTrackingRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/risk-disclosure': typeof LegalRiskDisclosureRoute
  '/legal/terms': typeof LegalTermsRoute
  '/stock/$symbol': typeof StockSymbolRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/aml-scan': typeof ApiPublicAmlScanRoute
  '/api/public/check-price-alerts': typeof ApiPublicCheckPriceAlertsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/command'
    | '/forgot-password'
    | '/history'
    | '/home'
    | '/kyc'
    | '/login'
    | '/markets'
    | '/mcp'
    | '/navigator'
    | '/orders'
    | '/pocket'
    | '/pools'
    | '/portfolio'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/trade'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/kyc'
    | '/admin/transactions'
    | '/api/candles'
    | '/api/fees'
    | '/api/mpesa-b2c-result'
    | '/api/mpesa-callback'
    | '/api/mpesa-status'
    | '/api/mpesa-stk'
    | '/api/quote'
    | '/api/trade'
    | '/api/wallet-invest'
    | '/api/withdraw-approve'
    | '/api/withdraw-request'
    | '/guides/dividend-tracking'
    | '/legal/privacy'
    | '/legal/risk-disclosure'
    | '/legal/terms'
    | '/stock/$symbol'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/aml-scan'
    | '/api/public/check-price-alerts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/command'
    | '/forgot-password'
    | '/history'
    | '/home'
    | '/kyc'
    | '/login'
    | '/markets'
    | '/mcp'
    | '/navigator'
    | '/orders'
    | '/pocket'
    | '/pools'
    | '/portfolio'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/trade'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/kyc'
    | '/admin/transactions'
    | '/api/candles'
    | '/api/fees'
    | '/api/mpesa-b2c-result'
    | '/api/mpesa-callback'
    | '/api/mpesa-status'
    | '/api/mpesa-stk'
    | '/api/quote'
    | '/api/trade'
    | '/api/wallet-invest'
    | '/api/withdraw-approve'
    | '/api/withdraw-request'
    | '/guides/dividend-tracking'
    | '/legal/privacy'
    | '/legal/risk-disclosure'
    | '/legal/terms'
    | '/stock/$symbol'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/aml-scan'
    | '/api/public/check-price-alerts'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/command'
    | '/forgot-password'
    | '/history'
    | '/home'
    | '/kyc'
    | '/login'
    | '/markets'
    | '/mcp'
    | '/navigator'
    | '/orders'
    | '/pocket'
    | '/pools'
    | '/portfolio'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/trade'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/kyc'
    | '/admin/transactions'
    | '/api/candles'
    | '/api/fees'
    | '/api/mpesa-b2c-result'
    | '/api/mpesa-callback'
    | '/api/mpesa-status'
    | '/api/mpesa-stk'
    | '/api/quote'
    | '/api/trade'
    | '/api/wallet-invest'
    | '/api/withdraw-approve'
    | '/api/withdraw-request'
    | '/guides/dividend-tracking'
    | '/legal/privacy'
    | '/legal/risk-disclosure'
    | '/legal/terms'
    | '/stock/$symbol'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/aml-scan'
    | '/api/public/check-price-alerts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CommandRoute: typeof CommandRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HistoryRoute: typeof HistoryRoute
  HomeRoute: typeof HomeRoute
  KycRoute: typeof KycRoute
  LoginRoute: typeof LoginRoute
  MarketsRoute: typeof MarketsRoute
  McpRoute: typeof McpRoute
  NavigatorRoute: typeof NavigatorRoute
  OrdersRoute: typeof OrdersRoute
  PocketRoute: typeof PocketRoute
  PoolsRoute: typeof PoolsRoute
  PortfolioRoute: typeof PortfolioRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TradeRoute: typeof TradeRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiCandlesRoute: typeof ApiCandlesRoute
  ApiFeesRoute: typeof ApiFeesRoute
  ApiMpesaB2cResultRoute: typeof ApiMpesaB2cResultRoute
  ApiMpesaCallbackRoute: typeof ApiMpesaCallbackRoute
  ApiMpesaStatusRoute: typeof ApiMpesaStatusRoute
  ApiMpesaStkRoute: typeof ApiMpesaStkRoute
  ApiQuoteRoute: typeof ApiQuoteRoute
  ApiTradeRoute: typeof ApiTradeRoute
  ApiWalletInvestRoute: typeof ApiWalletInvestRoute
  ApiWithdrawApproveRoute: typeof ApiWithdrawApproveRoute
  ApiWithdrawRequestRoute: typeof ApiWithdrawRequestRoute
  GuidesDividendTrackingRoute: typeof GuidesDividendTrackingRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRiskDisclosureRoute: typeof LegalRiskDisclosureRoute
  LegalTermsRoute: typeof LegalTermsRoute
  StockSymbolRoute: typeof StockSymbolRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicAmlScanRoute: typeof ApiPublicAmlScanRoute
  ApiPublicCheckPriceAlertsRoute: typeof ApiPublicCheckPriceAlertsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pools': {
      id: '/pools'
      path: '/pools'
      fullPath: '/pools'
      preLoaderRoute: typeof PoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pocket': {
      id: '/pocket'
      path: '/pocket'
      fullPath: '/pocket'
      preLoaderRoute: typeof PocketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigator': {
      id: '/navigator'
      path: '/navigator'
      fullPath: '/navigator'
      preLoaderRoute: typeof NavigatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command': {
      id: '/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof CommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/$symbol': {
      id: '/stock/$symbol'
      path: '/stock/$symbol'
      fullPath: '/stock/$symbol'
      preLoaderRoute: typeof StockSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/risk-disclosure': {
      id: '/legal/risk-disclosure'
      path: '/legal/risk-disclosure'
      fullPath: '/legal/risk-disclosure'
      preLoaderRoute: typeof LegalRiskDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/dividend-tracking': {
      id: '/guides/dividend-tracking'
      path: '/guides/dividend-tracking'
      fullPath: '/guides/dividend-tracking'
      preLoaderRoute: typeof GuidesDividendTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/withdraw-request': {
      id: '/api/withdraw-request'
      path: '/api/withdraw-request'
      fullPath: '/api/withdraw-request'
      preLoaderRoute: typeof ApiWithdrawRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/withdraw-approve': {
      id: '/api/withdraw-approve'
      path: '/api/withdraw-approve'
      fullPath: '/api/withdraw-approve'
      preLoaderRoute: typeof ApiWithdrawApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wallet-invest': {
      id: '/api/wallet-invest'
      path: '/api/wallet-invest'
      fullPath: '/api/wallet-invest'
      preLoaderRoute: typeof ApiWalletInvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trade': {
      id: '/api/trade'
      path: '/api/trade'
      fullPath: '/api/trade'
      preLoaderRoute: typeof ApiTradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quote': {
      id: '/api/quote'
      path: '/api/quote'
      fullPath: '/api/quote'
      preLoaderRoute: typeof ApiQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mpesa-stk': {
      id: '/api/mpesa-stk'
      path: '/api/mpesa-stk'
      fullPath: '/api/mpesa-stk'
      preLoaderRoute: typeof ApiMpesaStkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mpesa-status': {
      id: '/api/mpesa-status'
      path: '/api/mpesa-status'
      fullPath: '/api/mpesa-status'
      preLoaderRoute: typeof ApiMpesaStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mpesa-callback': {
      id: '/api/mpesa-callback'
      path: '/api/mpesa-callback'
      fullPath: '/api/mpesa-callback'
      preLoaderRoute: typeof ApiMpesaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mpesa-b2c-result': {
      id: '/api/mpesa-b2c-result'
      path: '/api/mpesa-b2c-result'
      fullPath: '/api/mpesa-b2c-result'
      preLoaderRoute: typeof ApiMpesaB2cResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fees': {
      id: '/api/fees'
      path: '/api/fees'
      fullPath: '/api/fees'
      preLoaderRoute: typeof ApiFeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/candles': {
      id: '/api/candles'
      path: '/api/candles'
      fullPath: '/api/candles'
      preLoaderRoute: typeof ApiCandlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof AdminRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/check-price-alerts': {
      id: '/api/public/check-price-alerts'
      path: '/api/public/check-price-alerts'
      fullPath: '/api/public/check-price-alerts'
      preLoaderRoute: typeof ApiPublicCheckPriceAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/aml-scan': {
      id: '/api/public/aml-scan'
      path: '/api/public/aml-scan'
      fullPath: '/api/public/aml-scan'
      preLoaderRoute: typeof ApiPublicAmlScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminKycRoute: typeof AdminKycRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminKycRoute: AdminKycRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CommandRoute: CommandRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HistoryRoute: HistoryRoute,
  HomeRoute: HomeRoute,
  KycRoute: KycRoute,
  LoginRoute: LoginRoute,
  MarketsRoute: MarketsRoute,
  McpRoute: McpRoute,
  NavigatorRoute: NavigatorRoute,
  OrdersRoute: OrdersRoute,
  PocketRoute: PocketRoute,
  PoolsRoute: PoolsRoute,
  PortfolioRoute: PortfolioRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TradeRoute: TradeRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiCandlesRoute: ApiCandlesRoute,
  ApiFeesRoute: ApiFeesRoute,
  ApiMpesaB2cResultRoute: ApiMpesaB2cResultRoute,
  ApiMpesaCallbackRoute: ApiMpesaCallbackRoute,
  ApiMpesaStatusRoute: ApiMpesaStatusRoute,
  ApiMpesaStkRoute: ApiMpesaStkRoute,
  ApiQuoteRoute: ApiQuoteRoute,
  ApiTradeRoute: ApiTradeRoute,
  ApiWalletInvestRoute: ApiWalletInvestRoute,
  ApiWithdrawApproveRoute: ApiWithdrawApproveRoute,
  ApiWithdrawRequestRoute: ApiWithdrawRequestRoute,
  GuidesDividendTrackingRoute: GuidesDividendTrackingRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRiskDisclosureRoute: LegalRiskDisclosureRoute,
  LegalTermsRoute: LegalTermsRoute,
  StockSymbolRoute: StockSymbolRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicAmlScanRoute: ApiPublicAmlScanRoute,
  ApiPublicCheckPriceAlertsRoute: ApiPublicCheckPriceAlertsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
